name: running e2e tests
on:
  workflow_call:

jobs:
  golangci:
    name: Running Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/.cache/golangci-lint
            ~/go/pkg
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - uses: actions/setup-go@v2
        with:
          # the version I am using
          go-version: "1.17.7"

      - uses: extractions/setup-just@v1

      - run: |
          just e2e
