name: Running E2E Tests
on:
  workflow_call:

jobs:
  e2e:
    name: Running End-To-End Tests
    runs-on: ubuntu-latest
    environment: e2e
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - uses: actions/setup-go@v2
        with:
          # the version I am using
          go-version: "1.17.7"

      - uses: extractions/setup-just@v1

      - name: Setup variables
        run: |
          echo "TESTING_WALLET_PRIVATE_KEY=${{ secrets.E2E_WALLET_PRIVATE_KEY }}"

      - name: Running End-to-End Testings
        run: |
          just e2e
