name: golangci-lint
on:
  workflow_call:
  push:
    branches: [main]
  pull_request:

jobs:
  golangci:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/.cache/golangci-lint
            ~/go/pkg
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - uses: golangci/golangci-lint-action@v2 
        with:
          version: latest
