name: Release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  call-workflow-linter:
    uses: ./.github/workflows/linter.yml

  call-workflow-test:
    uses: ./.github/workflows/test.yml

  # TODO: dont forget here
  # call-workflow-e2e:
  #   uses: ./.github/workflows/e2e.yml

  release-images:
    name: Building Image and Publishing
    needs: 
      - call-workflow-linter
      - call-workflow-test
      # I don't know why this step always got empty env to lead e2e private key cannot be loaded
      # but if you just run the same command in local, it will passed...
      # TODO: skip this until I find out a way...
      # - call-workflow-e2e
    runs-on: ubuntu-latest
    concurrency: ci-releasing-images
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/FindoraNetwork/refunder
          tags: |
            type=raw,value={{tag}}
            type=raw,value=latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
