name: Running Unit Tests
on:
  workflow_call:
  push:
    branches: [main]
  pull_request:

jobs:
  unit-tests:
    name: Running Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - uses: actions/setup-go@v2
        with:
          # the version I am using
          go-version: "1.17.7"

      - uses: extractions/setup-just@v1

      - run: |
          just test 
