name: running tests
on:
  push:
    tags: ["[0-9]+.[0-9]+.[0-9]+"]
    branches: [main]
  pull_request:

jobs:
  golangci:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/.cache/golangci-lint
            ~/go/pkg
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - uses: actions/setup-go@v2
        with:
          # the version I am using
          go-version: "1.17.7"

      - run: |
          go test --race ./...
